apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
      tier: frontend
      track: stable
  strategy:
    type: RollingUpdate
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
        track: stable
    spec:
      containers:
        - name: frontend
          image: "robertmaulana/frontend-svc:latest"
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: frontend
    tier: frontend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000