apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
      tier: backend
      track: stable
  strategy:
    type: RollingUpdate
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        track: stable
    spec:
      containers:
        - name: backend
          image: "robertmaulana/backend-svc:latest"
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: ClusterIP
  selector:
    app: backend
    tier: backend
  ports:
    - name: http
      port: 8080